## Test data for company

INSERT INTO `company` (`name`, `title`) VALUES ('Greenlight ITC', 'this is greenlight');
INSERT INTO `company` (`name`, `title`) VALUES ('Google', 'this is Google');
INSERT INTO `company` (`name`, `title`) VALUES ('Microsoft', 'this is Microsoft');
INSERT INTO `company` (`name`, `title`) VALUES ('Facebook', 'this is Facebook');


## Test data for directory

INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (2, 'Essie Vaill', '907-345-0962');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (2, 'Cruz Roudabush', '602-252-4827');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (2, 'Billie Vaill', '212-889-5775');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (2, 'Zackary Vaill', '732-442-0638');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (2, 'Rosemarie Fifield', '808-836-8966');

INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Bernard Laboy', '815-467-0487');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Sue Haakinson', '602-252-4827');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Valerie Pou', '212-889-5775');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Lashawn Hasty', '732-442-0638');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Marianne Earman', '808-836-8966');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (3, 'Justina Dragaj', '907-345-0962');

INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (4, 'Mandy Mcdonnell', '602-252-4827');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (4, 'Conrad Lanfear', '212-889-5775');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (4, 'Cyril Behen', '732-442-0638');
INSERT INTO `directory` (`company_id`, `name`, `telephone`) VALUES (4, 'Shelley Groden', '808-836-8966');